#Merchant API 
#ZipMoney Merchant API Initial build
#zipMoney Merchant API version: 2017-03-01


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZipMoney::CheckoutFeaturesTokenisation
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CheckoutFeaturesTokenisation' do
  before do
    # run before each test
    @instance = ZipMoney::CheckoutFeaturesTokenisation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutFeaturesTokenisation' do
    it 'should create an instact of CheckoutFeaturesTokenisation' do
      expect(@instance).to be_instance_of(ZipMoney::CheckoutFeaturesTokenisation)
    end
  end
  describe 'test attribute "required"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

